### ISSUE TITLE
Retour Correcteur

### ISSUE THREAD

**Issue by Abraham10000** [Nomena12/SAYNA-JSTSCANVAS-PANTHER-072022#1]
Beau travail mais il y a quelques détails à voir notamment le respect de la maquette données sur le formulaire et la carousel de la page home. Les liens de redirections vers les autres pages n'ont pas aussi marchés alors j'ai été obligé d'aller ouvrir un à un les pages via les fichiers HTML. Veuillez à ce que ce genre de problème n'arrive plus dans vos sites parce que ce sont des petites expériences utilisateurs basiques comme cela qui font les différences. 
Quand vous nommez des classes HTML, il est préférables de les mettre en anglais avec un certain sens qui aideront les autres à se repérer facilement dans vos codes. Et surtout, il est conseiller d'utiliser du snake_case et du kebab-case.
Structurer bien votre projet et mets les fichiers de mêmes types et fonction dans des mêmes dossiers.

**Comment by Nomena12** [comment]
Merci pour les corrections et les conseils.
